# Default initial positions for ur's ros2_control fake system

initial_positions:
  elbow_joint: 1.5
  robotiq_85_left_knuckle_joint: 0.002
  shoulder_lift_joint: -1.5
  shoulder_pan_joint: 0.16
  wrist_1_joint: -1.5
  wrist_2_joint: -1.5
  wrist_3_joint: -1.7